### PR TITLE
Ted2

### PR DESCRIPTION
**Pull request by ted-johnson**

### CODE REVIEW

**Comment by gokulavasan** [comment]
@ted-johnson Can you provide some description on what this PR is about?

**Comment by ted-johnson** [comment]
In the past, all timestamps have unsigned types.
In many places, the query compiler imputes that a function of a timestamp can also act as a timestamp.
Many times, the functions involve division and multiplication.
However, the multiplication (division) of a signed type with (by) another signed type has unpredictable results.

The code previously does not impute timestamp-ness if there is a division or multiplication if any of the types involved are signed.
We’ve used unsigned types as timestamps so this hasn’t been a problem.
Since java has problems with unsigned types, the timestamp is now likely to be a signed int or a signed long long.
The patch relaxes the conditions for imputing timestamp-ness so that one of the operands can be signed.

**Comment by gokulavasan** [comment]
@vshkap Can you review this PR? We can merge this after you give a thumbs up.

**Comment by vshkap** [comment]
LGTM

**Pull request merged**
