### PR TITLE
Changes to remove libcurl dependency

### PR DESCRIPTION
**Pull request by gokulavasan**
This PR contains the changes to remove libcurl dependency. Testing is in progress.

### CODE REVIEW

**Comment by vshkap** [comment]
I updated http client code to direct all error messages to stderr

**Comment by gokulavasan** [comment]
SQLFlowTest fix looks good to me. @achalpandey can you review the HubHttpHandler changes.

**Comment by gokulavasan** [comment]
@spatsch Can you review Vlad's code?

**Comment by achalpandey** [comment]
@gokulavasan HubHttpHandler LGTM

**Comment by gokulavasan** [comment]
Merging. Unit tests passed.

**Pull request merged**
