### PR TITLE
fill in the tigon-sql examples readme file

### PR DESCRIPTION
**Pull request by ted-johnson**

### CODE REVIEW

**Comment by gokulavasan** [comment]
https://issues.cask.co/browse/TIGON-128

**Comment by gokulavasan** [comment]
LGTM :+1:

**Comment by awholegunch** [comment]
I've altered the README (made it a markdown file, and added some text.) Please review.

**Comment by gokulavasan** [comment]
@awholegunch Thanks JJ. Looks good!

**Pull request merged**
