### PR TITLE
Changed binary build

### PR DESCRIPTION
**Pull request by achalpandey**
Had to change binary generation in the compiling phase because binary buildit script changed

### CODE REVIEW

**Comment by achalpandey** [comment]
Will checkin the updated linux tar ball once the bamboo build completes

**Comment by gokulavasan** [comment]
@achalpandey Did the build pass in bamboo? Can we include the linux tar ball? Ideally I would like to see AbstractInputFlowlet end-to-end test running on this branch before we merge it?

**Comment by achalpandey** [comment]
@gokulavasan  The bamboo build is brittle for now. working to fix that. I have already pulled in the AbstractInputFlowlet test into this branch. 

Waiting for the bamboo build to pass to update the linux tar ball.

**Comment by achalpandey** [comment]
SQL Library build instructions:

`mvn clean package -P sql-lib`

This command will compile all the SQL compiler code and generate a tar ball that will be packaged inside tigon-sql jar

**Comment by achalpandey** [comment]
@gokulavasan verified that when we run `mvn clean package -P sql-lib` the tigon-sql jar contains the new generated tar ball

**Comment by poornachandra** [comment]
LGTM :+1:

**Comment by achalpandey** [comment]
Bamboo Green! https://bamboo-prod.continuuity.com/browse/PRODRELALL-UNIT24

**Pull request merged**
