### PR TITLE
Revert "Tigon SQL changed interface setup"

### PR DESCRIPTION
**Pull request by gokulavasan**
Reverts caskdata/tigon#87

### CODE REVIEW

**Comment by gokulavasan** [comment]
Reverting the earlier PR to fix https://issues.cask.co/browse/TIGON-146

The fix will be made in a different PR soon.

**Comment by gokulavasan** [comment]
@achalpandey Can you review this PR?

https://builds.cask.co/browse/TIG-DBT0

**Comment by achalpandey** [comment]
Can you please confirm that this PR changes the tarballs to the old ones?
after that LGTM

**Comment by gokulavasan** [comment]
@achalpandey Yes, this reverts the entire PR. Once this PR is merged, develop will have old tarballs (from 0.2.0 release).

**Pull request merged**
